name: 🐛 Bug Report
description: Report a bug or issue with the Low Cost Browsing MCP Server
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs
      description: If applicable, add error logs to help explain your problem.
      placeholder: |
        ```
        Paste error logs here
        ```
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here or paste image URLs
    validations:
      required: false

  - type: dropdown
    id: environment-os
    attributes:
      label: 🖥️ Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: environment-node
    attributes:
      label: 📦 Node.js Version
      description: What version of Node.js are you using?
      placeholder: "e.g., 18.16.0"
    validations:
      required: true

  - type: input
    id: environment-npm
    attributes:
      label: 📦 npm Version
      description: What version of npm are you using?
      placeholder: "e.g., 9.5.1"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser (if applicable)
      description: Which browser were you using when the issue occurred?
      options:
        - Chromium
        - Firefox
        - WebKit/Safari
        - Multiple browsers
        - Not browser-related
    validations:
      required: false

  - type: dropdown
    id: llm-provider
    attributes:
      label: 🤖 LLM Provider (if applicable)
      description: Which LLM provider were you using?
      options:
        - OpenAI
        - Anthropic
        - Ollama
        - JAN AI
        - Multiple providers
        - Not LLM-related
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: ⚙️ Configuration
      description: Share your configuration (remove sensitive information like API keys)
      placeholder: |
        ```yaml
        browser:
          headless: true
          # ... other config
        ```
    validations:
      required: false

  - type: dropdown
    id: docker
    attributes:
      label: 🐳 Docker Usage
      description: Are you using Docker?
      options:
        - "Yes - Docker only"
        - "Yes - Docker and local"
        - "No - Local installation only"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I have removed any sensitive information (API keys, passwords, etc.)
          required: true
