name: Artifacts Fix

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID to download artifacts from'
        required: true
        type: string
      artifact_name:
        description: 'Artifact name to download'
        required: true
        type: string
        default: 'coverage-reports'

env:
  NODE_VERSION: '18'

jobs:
  download-artifacts:
    name: 📥 Download Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run_id }}
          merge-multiple: true
        continue-on-error: true

      - name: List downloaded files
        run: |
          echo "=== Downloaded Artifacts ==="
          if [ -d "artifacts" ]; then
            find artifacts -type f -exec ls -la {} \;
            echo "✅ Artifacts downloaded successfully"
          else
            echo "⚠️ No artifacts directory found"
          fi

      - name: Check artifact contents
        run: |
          if [ -d "artifacts" ]; then
            echo "=== Artifact Contents ==="
            tree artifacts/ || find artifacts -type f
          else
            echo "No artifacts to check"
          fi

      - name: Upload as new artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fixed-${{ github.event.inputs.artifact_name }}
          path: artifacts/
          retention-days: 30
